version: '3.4'

services:
  publisher:
    image: publisher
    build:
      context: .
      dockerfile: Publisher/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire.dashboard:18889
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 8181:8080

  publisher-sidecar:
    image: daprio/daprd:latest
    command: ["./daprd",
     "-app-id", "publisher",
     "-app-port", "8080",
     "-dapr-http-port", "3500",
     "-components-path", "/components"]
    volumes:
      - "./components:/components"
    depends_on:
      - publisher
    network_mode: "service:publisher"

  subscriber:
    image: subscriber
    build:
      context: .
      dockerfile: Subscriber/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire.dashboard:18889
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 8282:8080

  subscriber-sidecar:
    image: daprio/daprd:latest
    command: ["./daprd",
     "-app-id", "subscriber",
     "-app-port", "8080",
     "-dapr-http-port", "3500",
     "-components-path", "/components"]
    volumes:
      - "./components:/components"
    depends_on:
      - subscriber
    network_mode: "service:subscriber"
    
  aspire.dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318

  redis:
    image: redis:latest
    ports:
      - 6500:6379

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672